### ISSUE TITLE
Could an auto-update of the latest data be made please ?

### ISSUE THREAD

**Issue by AkechiShiro** [karimhabush/cyberowl#102]
Hi,
I may be wrong but I believe the latest data seems to be dating back from a month ago/5 May 2023 ?

**Comment by karimhabush** [comment]
Hello @AkechiShiro, a lot of people reported this actually, but it's only a cache-related issue. A simple solution to this problem is to perform a hard reload of the page. 

I will work on this further to change the caching bahavior. 

Thank you so much for the notice!

**Comment by AkechiShiro** [comment]
Perhaps an update to the README should mention this.

If you need, I can send a PR for this but it is just a quick note so others don't reopen an issue about this.

I probably didn't check hard enough already closed issues mentioning this issue

**Comment by karimhabush** [comment]
Hello @AkechiShiro, sorry for the late response, I had a busy week...😅
I've worked on this the other day, so I think it should be fixed by now 🤞

**Comment by AkechiShiro** [comment]
I believe this issue is indeed fixed, thanks !
